- op: add
  path: /parameters/0
  value:
    name: IMAGE_PULL_POLICY
    value: "Never"
- op: add
  path: /parameters/0
  value:
    name: VALKEY_STORAGE
    value: 8Gi
- op: add
  path: /parameters/0
  value:
    name: VALKEY_PVC_NAME
    value: valkey-data
- op: add
  path: /parameters/0
  value:
    name: VALKEY_IMAGE_NAME
    value: quay.io/sclorg/valkey-7-c10s
- op: add
  path: /parameters/0
  value:
    name: VALKEY_IMAGE_TAG
    value: bf91acf0827dc5db216164aafe3d34beb245dcec
- op: add
  path: /parameters/0
  value:
    name: OPENSEARCH_CURATOR_LOGLEVEL
    value: "DEBUG"
- op: add
  path: /parameters/0
  value:
    name: LOG_LEVEL
    value: debug
- op: add
  path: /parameters/0
  value:
    name: ONPREM_LOGLEVEL
    value: "debug"
