- op: add
  path: /parameters/0
  value:
    name: IMAGE_PULL_POLICY
    value: "Never"
- op: add
  path: /parameters/0
  value:
    name: REDIS_STORAGE
    value: 8Gi
- op: add
  path: /parameters/0
  value:
    name: REDIS_PVC_NAME
    value: redis-data
- op: add
  path: /parameters/0
  value:
    name: REDIS_IMAGE_NAME
    value: quay.io/edge-infrastructure/redis
- op: add
  path: /parameters/0
  value:
    name: REDIS_IMAGE_TAG
    value: 6.2.7-debian-10-r23
- op: add
  path: /parameters/0
  value:
    name: REDIS_EXPORTER_IMAGE_NAME
    value: quay.io/edge-infrastructure/redis-exporter
- op: add
  path: /parameters/0
  value:
    name: REDIS_EXPORTER_IMAGE_TAG
    value: 1.37.0-debian-10-r63
- op: add
  path: /parameters/0
  value:
    name: OPENSEARCH_CURATOR_LOGLEVEL
    value: "DEBUG"
- op: add
  path: /parameters/0
  value:
    name: LOG_LEVEL
    value: debug
- op: add
  path: /parameters/0
  value:
    name: ONPREM_LOGLEVEL
    value: "debug"
