apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    group: template.openshift.io
    kind: Template
    version: v1
    name: assisted-events-stream-projection
  path: redis.yaml
