- op: add
  path: /parameters/0
  value:
    name: IMAGE_PULL_POLICY
    value: "Always"
- op: add
  path: /parameters/0
  value:
    name: VALKEY_STORAGE
    value: "100Gi"
- op: add
  path: /parameters/0
  value:
    name: VALKEY_PVC_NAME
    value: valkey-data
- op: add
  path: /parameters/0
  value:
    name: VALKEY_IMAGE_NAME
    value: quay.io/sclorg/valkey-7-c10s
- op: add
  path: /parameters/0
  value:
    name: VALKEY_IMAGE_TAG
    value: bf91acf0827dc5db216164aafe3d34beb245dcec
- op: add
  path: /parameters/0
  value:
    name: OPENSEARCH_CURATOR_LOGLEVEL
    value: "INFO"
- op: add
  path: /parameters/0
  value:
    name: LOG_LEVEL
    value: info
- op: add
  path: /parameters/0
  value:
    name: ONPREM_LOGLEVEL
    value: "info"
- op: add
  path: /parameters/0
  value:
    name: VALKEY_CPU_LIMIT
    value: "1"
- op: add
  path: /parameters/0
  value:
    name: VALKEY_CPU_REQUEST
    value: "50m"
- op: add
  path: /parameters/0
  value:
    name: VALKEY_MEMORY_LIMIT
    value: "6Gi"
- op: add
  path: /parameters/0
  value:
    name: VALKEY_MEMORY_REQUEST
    value: "5Gi"
